{
 "title": "Simple Meli-Proxy Dashboard",
 "tags": [
  "meli-proxy",
  "simple"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "meli_proxy_requests_total", "legendFormat": "{{path}} - {{status}}" }
   ]
  },
  {
   "title": "Categories Endpoint - Total Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meli_proxy_requests_total{path=\"/categories/*\"}",
     "legendFormat": "Categories Endpoint"
    }
   ]
  },
  {
   "title": "No Rate Limit Endpoint - Total Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meli_proxy_requests_total{path=\"/no-ratelimit/*\"}",
     "legendFormat": "No Rate Limit Endpoint"
    }
   ]
  },
  {
   "title": "Distribución de Requests por Endpoint",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meli_proxy_requests_total", "legendFormat": "{{path}}" }
   ]
  }
 ]
}