{
 "title": "Meli-Proxy Logs Dashboard",
 "tags": [
  "meli-proxy",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs por Contenedor",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_name) (count_over_time({job=\"containerlogs\"}[5m]))"
    }
   ]
  },
  {
   "title": "Logs de Meli-Proxy",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |= \"proxy\""
    }
   ]
  },
  {
   "title": "Todos los Logs del Sistema",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"}"
    }
   ]
  }
 ]
}